### PR TITLE
Fix #9 and #11

### LINKED ISSUE #9: Invalid HTML (services/users/api/templates/index.html)
There are two dangling closing tags near the bottom:

image

### PR DESCRIPTION
**Pull request by anson-vandoren**
Fixes invalid HTML (Issue #9) and wrong entrypoint (Issue #10)

### CODE REVIEW

**Comment by mjhea0** [comment]
@anson-vandoren - so the code is broken up by part: https://github.com/testdrivenio/testdriven-app-2.4/releases. Each of the tags represents the code at the end of the part. Since you're on part one, compare the code you have at the end of the part to the code here: https://github.com/testdrivenio/testdriven-app-2.4/tree/part1.

Does that help?

**Comment by anson-vandoren** [comment]
Based on the tag for Part 1:

1. `/services/users/Dockerfile-prod` line 18 should copy from `./entrypoint-prod.sh`, not `./entrypoint.sh`
2. The extra </div> and </script> tags should be removed from `/services/users/project/api/templates/index.html` (lines 51 and 52)

**Comment by mjhea0** [comment]
It should be copying from `entrypoint.sh` based on the text here: https://testdriven.io/courses/microservices-with-docker-flask-and-react/part-one-deployment/

**Comment by mjhea0** [comment]
I'm closing this PR

**Comment by anson-vandoren** [comment]
@mjhea0 The text you linked is wrong. You created a entrypoint-prod.sh file that used gunicorn instead of flask server to use in production. So the Dockerfile-prod should be using entrypoint-prod.sh (with gunicorn), and not entrypoint.sh (with flask).

**Pull request closed without merging**
